Downloading dataset...

Columns in dataset:
['opendata_id', 'city', 'postcode', 'latitude', 'longitude', 'ihk_branch_id', 'nace_id', 'branch_top_level_id', 'employees_range', 'ihk_branch_desc', 'nace_desc', 'branch_top_level_desc', 'business_age', 'business_type', 'Bezirk', 'planungsraum_id', 'Planungsraum', 'Bezirksregion', 'Prognoseraum', 'Ortsteil']

Initial shape: (360216, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360216 entries, 0 to 360215
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   opendata_id            360216 non-null  int64
 1   city                   360216 non-null  object
 2   postcode               360216 non-null  int64
 3   latitude               360209 non-null  float64
 4   longitude              360209 non-null  float64
 5   ihk_branch_id          360128 non-null  float64
 6   nace_id                360128 non-null  float64
 7   branch_top_level_id    360128 non-null  float64
 8   employees_range        360216 non-null  object
 9   ihk_branch_desc        360123 non-null  object
 10  nace_desc              359981 non-null  object
 11  branch_top_level_desc  360024 non-null  object
 12  business_age           359300 non-null  float64
 13  business_type          360216 non-null  object
 14  Bezirk                 360198 non-null  object
 15  planungsraum_id        360198 non-null  float64
 16  Planungsraum           360198 non-null  object
 17  Bezirksregion          360198 non-null  object
 18  Prognoseraum           360198 non-null  object
 19  Ortsteil               344937 non-null  object
dtypes: float64(7), int64(2), object(11)
memory usage: 55.0+ MB

(360116, 21)

In [ ]:
# Project: Berlin Business Landscape Analysis
# Data Source: IHK Berlin Open Data (CC0 1.0)
# Description: This script cleans raw data for Tableau visualisation

# STEP 1 - Load dataset (correct Git LFS URL)

In [15]:
import pandas as pd
url = r"https://media.githubusercontent.com/media/IHKBerlin/IHKBerlin_Gewerbedaten/master/data/IHKBerlin_Gewerbedaten.csv"

print("Downloading dataset...")
df = pd.read_csv(url, encoding="utf-8")

print("\nColumns in dataset:")
print(df.columns.tolist())
print("\nInitial shape:", df.shape)

Downloading dataset...

Columns in dataset:
['opendata_id', 'city', 'postcode', 'latitude', 'longitude', 'ihk_branch_id', 'nace_id', 'branch_top_level_id', 'employees_range', 'ihk_branch_desc', 'nace_desc', 'branch_top_level_desc', 'business_age', 'business_type', 'Bezirk', 'planungsraum_id', 'Planungsraum', 'Bezirksregion', 'Prognoseraum', 'Ortsteil']

Initial shape: (360216, 20)


# STEP 2 - View the Dataset

In [16]:
df.head()

,opendata_id,city,postcode,latitude,longitude,ihk_branch_id,nace_id,branch_top_level_id,employees_range,ihk_branch_desc,nace_desc,branch_top_level_desc,business_age,business_type,Bezirk,planungsraum_id,Planungsraum,Bezirksregion,Prognoseraum,Ortsteil
0,572114,Berlin,10179,52.513315,13.411584,65122.0,6512.0,65.0,0 Beschäftigte,Schaden- und Unfallversicherungen,Nichtlebensversicherungen,"Versicherungen, Rückversicherungen und Pension...",41.0,im Handelsregister eingetragen,Mitte,1100312.0,Heine-Viertel West,Alexanderplatz,Zentrum,Mitte
1,6063606,Berlin,10713,52.488714,13.303514,562202.0,5622.0,56.0,0 Beschäftigte,Kantinen,Sonstige Caterer und Erbringung sonstiger Verp...,Gastronomie,0.0,im Handelsregister eingetragen,Charlottenburg-Wilmersdorf,4500939.0,Eisenzahnstraße,Halensee,Wilmersdorf Zentrum,Wilmersdorf
2,131831318,Berlin,10713,52.479296,13.319051,47403.0,4740.0,47.0,0 Beschäftigte,Einzelhandel mit Geräten der Unterhaltungselek...,Einzelhandel mit Geräten der Informations- und...,Einzelhandel,41.0,im Handelsregister eingetragen,Charlottenburg-Wilmersdorf,4501148.0,Brabanter Platz,Volkspark Wilmersdorf,Wilmersdorf Zentrum,Wilmersdorf
3,943032071440,Berlin,12047,52.486200,13.429312,731103.0,7311.0,73.0,0 Beschäftigte,Promotion,Tätigkeiten von Werbeagenturen,Werbung und Marktforschung sowie Public-Relati...,14.0,Kleingewerbetreibender,Neukölln,8100314.0,Donaustraße,Reuterstraße,Neukölln,Neukölln
4,927439271464,Berlin,12435,52.492207,13.451324,47811.0,4781.0,47.0,1 - 3 Beschäftigte,Einzelhandel mit Kraftwagen mit einem zulässig...,Einzelhandel mit Kraftwagen,Einzelhandel,11.0,im Handelsregister eingetragen,Treptow-Köpenick,9100101.0,Alt-Treptow,Alt-Treptow,Treptow-Köpenick 1,Alt-Treptow

# STEP 3 - Inspect the Data

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360216 entries, 0 to 360215
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   opendata_id            360216 non-null  int64
 1   city                   360216 non-null  object
 2   postcode               360216 non-null  int64
 3   latitude               360209 non-null  float64
 4   longitude              360209 non-null  float64
 5   ihk_branch_id          360128 non-null  float64
 6   nace_id                360128 non-null  float64
 7   branch_top_level_id    360128 non-null  float64
 8   employees_range        360216 non-null  object
 9   ihk_branch_desc        360123 non-null  object
 10  nace_desc              359981 non-null  object
 11  branch_top_level_desc  360024 non-null  object
 12  business_age           359300 non-null  float64
 13  business_type          360216 non-null  object
 14  Bezirk                 360198 non-null  object
 15  planungsraum_id        360198 non-null  float64
 16  Planungsraum           360198 non-null  object
 17  Bezirksregion          360198 non-null  object
 18  Prognoseraum           360198 non-null  object
 19  Ortsteil               344937 non-null  object
dtypes: float64(7), int64(2), object(11)
memory usage: 55.0+ MB

# STEP 4 - Validate required columns

In [18]:
required_cols = ["longitude", "latitude", "ihk_branch_desc"]

missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise ValueError(f"Dataset is missing required columns: {missing}")

# STEP 5 - Drop rows missing coordinates or industry

In [19]:
df = df.dropna(subset=["longitude", "latitude", "ihk_branch_desc"])

# STEP 6 - Clean employees_range

In [20]:
df["employees_range"] = df["employees_range"].fillna("Unknown")

# STEP 7 - Create simplified industry name

In [21]:
df["industry_clean"] = df["ihk_branch_desc"].astype(str).str.split(",").str[0]

# STEP 8 - Convert business_age to numeric

In [22]:
df["business_age"] = pd.to_numeric(df["business_age"], errors="coerce")

# STEP 9 - Handle Missing Value

In [23]:
df.isna().sum()

opendata_id                  0
city                         0
postcode                     0
latitude                     0
longitude                    0
ihk_branch_id                0
nace_id                      0
branch_top_level_id          0
employees_range              0
ihk_branch_desc              0
nace_desc                  142
branch_top_level_desc      104
business_age               916
business_type                0
Bezirk                      11
planungsraum_id             11
Planungsraum                11
Bezirksregion               11
Prognoseraum                11
Ortsteil                 15266
industry_clean               0
dtype: int64

# STEP 10 - Remove Duplicates

In [24]:
df.shape

(360116, 21)

In [25]:

df = df.drop_duplicates()

In [26]:

df.shape

(360116, 21)

# STEP 11 - Final inspection

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 360116 entries, 0 to 360215
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   opendata_id            360116 non-null  int64
 1   city                   360116 non-null  object
 2   postcode               360116 non-null  int64
 3   latitude               360116 non-null  float64
 4   longitude              360116 non-null  float64
 5   ihk_branch_id          360116 non-null  float64
 6   nace_id                360116 non-null  float64
 7   branch_top_level_id    360116 non-null  float64
 8   employees_range        360116 non-null  object
 9   ihk_branch_desc        360116 non-null  object
 10  nace_desc              359974 non-null  object
 11  branch_top_level_desc  360012 non-null  object
 12  business_age           359200 non-null  float64
 13  business_type          360116 non-null  object
 14  Bezirk                 360105 non-null  object
 15  planungsraum_id        360105 non-null  float64
 16  Planungsraum           360105 non-null  object
 17  Bezirksregion          360105 non-null  object
 18  Prognoseraum           360105 non-null  object
 19  Ortsteil               344850 non-null  object
 20  industry_clean         360116 non-null  object
dtypes: float64(7), int64(2), object(12)
memory usage: 60.4+ MB

In [28]:
df.head()

,opendata_id,city,postcode,latitude,longitude,ihk_branch_id,nace_id,branch_top_level_id,employees_range,ihk_branch_desc,...,branch_top_level_desc,business_age,business_type,Bezirk,planungsraum_id,Planungsraum,Bezirksregion,Prognoseraum,Ortsteil,industry_clean
0,572114,Berlin,10179,52.513315,13.411584,65122.0,6512.0,65.0,0 Beschäftigte,Schaden- und Unfallversicherungen,...,"Versicherungen, Rückversicherungen und Pension...",41.0,im Handelsregister eingetragen,Mitte,1100312.0,Heine-Viertel West,Alexanderplatz,Zentrum,Mitte,Schaden- und Unfallversicherungen
1,6063606,Berlin,10713,52.488714,13.303514,562202.0,5622.0,56.0,0 Beschäftigte,Kantinen,...,Gastronomie,0.0,im Handelsregister eingetragen,Charlottenburg-Wilmersdorf,4500939.0,Eisenzahnstraße,Halensee,Wilmersdorf Zentrum,Wilmersdorf,Kantinen
2,131831318,Berlin,10713,52.479296,13.319051,47403.0,4740.0,47.0,0 Beschäftigte,Einzelhandel mit Geräten der Unterhaltungselek...,...,Einzelhandel,41.0,im Handelsregister eingetragen,Charlottenburg-Wilmersdorf,4501148.0,Brabanter Platz,Volkspark Wilmersdorf,Wilmersdorf Zentrum,Wilmersdorf,Einzelhandel mit Geräten der Unterhaltungselek...
3,943032071440,Berlin,12047,52.486200,13.429312,731103.0,7311.0,73.0,0 Beschäftigte,Promotion,...,Werbung und Marktforschung sowie Public-Relati...,14.0,Kleingewerbetreibender,Neukölln,8100314.0,Donaustraße,Reuterstraße,Neukölln,Neukölln,Promotion
4,927439271464,Berlin,12435,52.492207,13.451324,47811.0,4781.0,47.0,1 - 3 Beschäftigte,Einzelhandel mit Kraftwagen mit einem zulässig...,...,Einzelhandel,11.0,im Handelsregister eingetragen,Treptow-Köpenick,9100101.0,Alt-Treptow,Alt-Treptow,Treptow-Köpenick 1,Alt-Treptow,Einzelhandel mit Kraftwagen mit einem zulässig...

# STEP 12 — Export Clean CSV file

In [29]:
df.to_csv("cleaned_ihk_data.csv", index=False)